name: Release workflow frontend

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: search-gift
    strategy:
      matrix:
        node-version: [15.x]
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        working-directory: ./frontend
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - name: Deploy to Heroku (Frontend)
        uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
            heroku_email: ${{ secrets.HEROKU_EMAIL }}
            usedocker: true
            appdir: "frontend"
